[package]
name = "proto"
version = "0.1.0"
edition = "2024"

[build-dependencies]
tonic-build = "*"

[dependencies]
prost = "0.13.5"
tonic = "0.13.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
